### ISSUE TITLE
A better mobile version, maybe?

### ISSUE THREAD

**Issue by Raiondesu** [VeryWow/v-oogle#1]
Currently, the mobile version of the site is nowhere near the one of google.com. It's merely a collapsed desktop version instead.

Maybe, we can do better?

**Comment by kaskar2008** [comment]
@Raiondesu ofc we can do better 😁

**Comment by kaskar2008** [comment]
@Raiondesu On the other hand - we're fine :)
May I close it for now?

**Comment by Raiondesu** [comment]
@kaskar2008 Okay
